### PR TITLE
Update 11000739.yaml

### PR DESCRIPTION
**Pull request by fila612**
added ids from original Tonie

### CODE REVIEW

**Comment by SciLor** [comment]
The syntax is wrong, please check with this example: https://github.com/toniebox-reverse-engineering/tonies-json/blob/master/yaml/05-0003.yaml

confidence must be 0 as it is not automatically validated by a dumped tonie.

**Comment by fila612** [comment]
thanks for that review - I've updated all 3 PRs into needed syntax.

**Comment by SciLor** [comment]
Please correct the indentation.

**Comment by fila612** [comment]
does it fit now? copied from example again.

**Pull request merged**
